### PR TITLE
PAXTRANSX-10: Add proof to TransactionSupportLevel before recovery

### PR DESCRIPTION
**Pull request by graben**

### CODE REVIEW

**Comment by graben** [comment]
Hi @grgrzybek : Could you please have a look on this?

**Comment by graben** [comment]
@grgrzybek : I add some itests to validate localtransaction support works for jdbc

**Comment by grgrzybek** [comment]
Thanks Benjamin - I'm sorry for huge delay - I'll really look at pax-*
projects next week ;)

regards
Grzegorz Grzybek

sob., 23 mar 2019 o 17:08 Benjamin Graf <notifications@github.com>
napisał(a):

**Comment by grgrzybek** [comment]
my bad (too many tasks to do recently). you just prevented registration **for recovery**...

**Pull request merged**
